category1 = Category.create(name:"レディース")
category2 = Category.create(name:"メンズ")
category3 = Category.create(name:"ベビー・キッズ")
category4 = Category.create(name:"インテリア・住まい・小物")
category5 = Category.create(name:"本・音楽・ゲーム")
category6 = Category.create(name:"おもちゃ・ホビー・グッズ")
category7 = Category.create(name:"コスメ・香水・美容")
category8 = Category.create(name:"家電・スマホ・カメラ")
category9 = Category.create(name:"スポーツ・レジャー")
category10 = Category.create(name:"ハンドメイド")
category11 = Category.create(name:"チケット")
category12 = Category.create(name:"自動車・オートバイ")
category13 = Category.create(name:"その他")
category1_1 = category1.children.create(name:"トップス")
category1_2 = category1.children.create(name:"ジャケット/アウター")
category1_3 = category1.children.create(name:"パンツ")
category1_4 = category1.children.create(name:"スカート")
category1_5 = category1.children.create(name:"ワンピース")
category1_6 = category1.children.create(name:"靴")
category1_7 = category1.children.create(name:"ルームウェア/パジャマ")
category1_8 = category1.children.create(name:"レッグウェア")
category1_9 = category1.children.create(name:"帽子")
category1_10 = category1.children.create(name:"バッグ")
category1_11 = category1.children.create(name:"アクセサリー")
category1_12 = category1.children.create(name:"ヘアアクセサリー")
category1_13 = category1.children.create(name:"小物")
category1_14 = category1.children.create(name:"時計")
category1_15 = category1.children.create(name:"ウィッグ/エクステ")
category1_16 = category1.children.create(name:"浴衣/水着")
category1_17 = category1.children.create(name:"スーツ/フォーマル/ドレス")
category1_18 = category1.children.create(name:"マタニティ")
category1_19 = category1.children.create(name:"その他")
category2_1 = category2.children.create(name:"トップス")
category2_2 = category2.children.create(name:"ジャケット/アウター")
category2_3 = category2.children.create(name:"パンツ")
category2_4 = category2.children.create(name:"靴")
category2_5 = category2.children.create(name:"バッグ")
category2_6 = category2.children.create(name:"スーツ")
category2_7 = category2.children.create(name:"帽子")
category2_8 = category2.children.create(name:"アクセサリー")
category2_9 = category2.children.create(name:"小物")
category2_10 = category2.children.create(name:"時計")
category2_11 = category2.children.create(name:"水着")
category2_12 = category2.children.create(name:"レッグウェア")
category2_13 = category2.children.create(name:"アンダーウェア")
category2_14 = category2.children.create(name:"その他")
category3_1 = category3.children.create(name:"ベビー服(女の子用~95cm)")
category3_2 = category3.children.create(name:"ベビー服(男の子用~95cm)")
category3_3 = category3.children.create(name:"ベビー服(男女兼用~95cm)")
category3_4 = category3.children.create(name:"ベビー服(女の子用~100cm)")
category3_5 = category3.children.create(name:"ベビー服(男の子用~100cm)")
category3_6 = category3.children.create(name:"ベビー服(男女兼用~100cm)")
category3_7 = category3.children.create(name:"キッズ靴")
category3_8 = category3.children.create(name:"子供用ファッション小物")
category3_9 = category3.children.create(name:"おむつ/トイレ/バス")
category3_10 = category3.children.create(name:"外出/移動用品")
category3_11 = category3.children.create(name:"授乳/食事")
category3_12 = category3.children.create(name:"ベビー家具/寝具/室内用品")
category3_13 = category3.children.create(name:"おもちゃ")
category3_14 = category3.children.create(name:"行事/記念品")
category3_15 = category3.children.create(name:"その他")
category4_1 = category4.children.create(name:"キッチン/食器")
category4_2 = category4.children.create(name:"ベッド/マットレス")
category4_3 = category4.children.create(name:"ソファ/ソファベッド")
category4_4 = category4.children.create(name:"椅子/チェア")
category4_5 = category4.children.create(name:"机/テーブル")
category4_6 = category4.children.create(name:"収納家具")
category4_7 = category4.children.create(name:"ラグ/カーペット/マット")
category4_8 = category4.children.create(name:"カーテン/ブラインド")
category4_9 = category4.children.create(name:"ライト/照明")
category4_10 = category4.children.create(name:"寝具")
category4_11 = category4.children.create(name:"インテリア小物")
category4_12 = category4.children.create(name:"季節/年中行事")
category4_13 = category4.children.create(name:"その他")
category5_1 = category5.children.create(name:"本")
category5_2 = category5.children.create(name:"漫画")
category5_3 = category5.children.create(name:"雑誌")
category5_4 = category5.children.create(name:"CD")
category5_5 = category5.children.create(name:"DVD/ブルーレイ")
category5_6 = category5.children.create(name:"レコード")
category5_7 = category5.children.create(name:"テレビゲーム")
category6_1 = category6.children.create(name:"おもちゃ")
category6_2 = category6.children.create(name:"タレットグッズ")
category6_3 = category6.children.create(name:"コミック/アニメグッズ")
category6_4 = category6.children.create(name:"トレーディングカード")
category6_5 = category6.children.create(name:"フィギュア")
category6_6 = category6.children.create(name:"楽器/機材")
category6_7 = category6.children.create(name:"コレクション")
category6_8 = category6.children.create(name:"ミリタリー")
category6_9 = category6.children.create(name:"美術品")
category6_10 = category6.children.create(name:"アート用品")
category6_11 = category6.children.create(name:"その他")
category7_1 = category7.children.create(name:"ベースメイク")
category7_2 = category7.children.create(name:"メイクアップ")
category7_3 = category7.children.create(name:"ネイルケア")
category7_4 = category7.children.create(name:"香水")
category7_5 = category7.children.create(name:"スキンケア/基礎化粧品")
category7_6 = category7.children.create(name:"ヘアケア")
category7_7 = category7.children.create(name:"ボディケア")
category7_8 = category7.children.create(name:"オーラルケア")
category7_9 = category7.children.create(name:"リラクゼーション")
category7_10 = category7.children.create(name:"ダイエット")
category7_11 = category7.children.create(name:"その他")
category8_1 = category8.children.create(name:"スマートフォン/携帯電話")
category8_2 = category8.children.create(name:"スマホアクセサリー")
category8_3 = category8.children.create(name:"PC/タブレット")
category8_4 = category8.children.create(name:"カメラ")
category8_5 = category8.children.create(name:"テレビ/映像機器")
category8_6 = category8.children.create(name:"オーディオ機器")
category8_7 = category8.children.create(name:"美容/健康")
category8_8 = category8.children.create(name:"冷蔵庫/空調")
category8_9 = category8.children.create(name:"生活家電")
category8_10 = category8.children.create(name:"その他")
category9_1 = category9.children.create(name:"ゴルフ")
category9_2 = category9.children.create(name:"フィッシング")
category9_3 = category9.children.create(name:"自転車")
category9_4 = category9.children.create(name:"トレーニング/エクササイズ")
category9_5 = category9.children.create(name:"野球")
category9_6 = category9.children.create(name:"サッカー/フットサル")
category9_7 = category9.children.create(name:"テニス")
category9_8 = category9.children.create(name:"スノーボード")
category9_9 = category9.children.create(name:"スキー")
category9_10 = category9.children.create(name:"その他スポーツ")
category9_11 = category9.children.create(name:"アウトドア")
category9_12 = category9.children.create(name:"その他")
category10_1 = category10.children.create(name:"アクセサリー(女性用)")
category10_2 = category10.children.create(name:"ファッション/小物")
category10_3 = category10.children.create(name:"アクセサリー/時計")
category10_4 = category10.children.create(name:"日用品/インテリア")
category10_5 = category10.children.create(name:"趣味/おもちゃ")
category10_6 = category10.children.create(name:"キッズ/ベビー")
category10_7 = category10.children.create(name:"素材/材料")
category10_8 = category10.children.create(name:"二次創作物")
category10_9 = category10.children.create(name:"その他")
category11_1 = category11.children.create(name:"音楽")
category11_2 = category11.children.create(name:"スポーツ")
category11_3 = category11.children.create(name:"演劇/芸能")
category11_4 = category11.children.create(name:"イベント")
category11_5 = category11.children.create(name:"映画")
category11_6 = category11.children.create(name:"施設利用券")
category11_7 = category11.children.create(name:"優待券/割引券")
category11_8 = category11.children.create(name:"その他")
category12_1 = category12.children.create(name:"自動車本体")
category12_2 = category12.children.create(name:"自動車タイヤ/ホイール")
category12_3 = category12.children.create(name:"自動車パーツ")
category12_4 = category12.children.create(name:"自動車アクセサリー")
category12_5 = category12.children.create(name:"オートバイ車体")
category12_6 = category12.children.create(name:"オートバイパーツ")
category12_7 = category12.children.create(name:"オートバイアクセサリー")
category13_1 = category13.children.create(name:"まとめ売り")
category13_2 = category13.children.create(name:"ペット用品")
category13_3 = category13.children.create(name:"食品")
category13_4 = category13.children.create(name:"飲料/酒")
category13_5 = category13.children.create(name:"日用品/生活雑貨/旅行")
category13_6 = category13.children.create(name:"アンティーク/コレクション")
category13_7 = category13.children.create(name:"文房具/事務用品")
category13_8 = category13.children.create(name:"事務/店舗用品")
category13_9 = category13.children.create(name:"その他")
category1_1.children.create([{name:"Tシャツ/カットソー(半袖/袖なし)"},{name:"Tシャツ/カットソー(七分/長袖)"},{name:"シャツ/ブラウス()半袖/袖なし"},{name:"シャツ/ブラウス(七分/長袖)"},{name:"ポロシャツ"},{name:"キャミソール"},{name:"タンクトップ"},{name:"ホルターネック"},{name:"ニットセーター"},{name:"チュニック"},{name:"カーディガン/ボレロ"},{name:"アンサンブル"},{name:"ベスト/ジレ"},{name:"パーカー"},{name:"トレーナー/スウェット"},{name:"ベアトップ/チューブトップ"},{name:"ジャージ"},{name:"その他"}])
category1_2.children.create([{name:"テーラードジャケット"},{name:"ノーカラージャケット"},{name:"Gジャン/デニムジャケット"},{name:"レザージャケット"},{name:"ダウンジャケット"},{name:"ライダースジャケット"},{name:"ミリタリージャケット"},{name:"ダウンベスト"},{name:"ジャンバー/ブルゾン"},{name:"ポンチョ"},{name:"ロングコート"},{name:"トレンチコート"},{name:"ダッフルコート"},{name:"ピーコート"},{name:"チェスターコート"},{name:"モッズコート"},{name:"スタジャン"},{name:"毛皮/ファーコート"},{name:"スプリングコート"},{name:"スカジャン"},{name:"その他"}])
category1_3.children.create([{name:"デニム/ジーンズ"},{name:"ショートパンツ"},{name:"カジュアルパンツ"},{name:"ハーフパンツ"},{name:"チノパン"},{name:"ワークパンツ/カーゴパンツ"},{name:"クロップドパンツ"},{name:"サロペット/オーバーオール"},{name:"オールインワン"},{name:"サルエルパンツ"},{name:"ガウチョパンツ"},{name:"その他"}])
category1_4.children.create([{name:"ミニスカート"},{name:"ひざ丈スカート"},{name:"ロングスカート"},{name:"キュロット"},{name:"その他"}])
category1_5.children.create([{name:"ミニワンピース"},{name:"ひざ丈ワンピース"},{name:"ロングワンピース"},{name:"その他"}])
category1_6.children.create([{name:"ハイヒール/パンプス"},{name:"ブーツ"},{name:"サンダル"},{name:"スニーカー"},{name:"ミュール"},{name:"モカシン"},{name:"ローファー/革靴"},{name:"フラットシューズ/バレエシューズ"},{name:"長靴/レインシューズ"},{name:"その他"}])
category1_7.children.create([{name:"パジャマ"},{name:"ルームウェア"}])
category1_8.children.create([{name:"ソックス"},{name:"スパッツ/レギンス"},{name:"ストキング/タイツ"},{name:"レッグウォーマー"},{name:"その他"}])
category1_9.children.create([{name:"ニットキャップ/ビーニー"},{name:"ハット"},{name:"ハンチング/ベレー帽"},{name:"キャップ"},{name:"キャスケット"},{name:"麦わら帽子"},{name:"その他"}])
category1_10.children.create([{name:"ハンドバッグ"},{name:"トートバッグ"},{name:"エコバッグ"},{name:"リュック/バックパック"},{name:"ボストンバッグ"},{name:"スポーツバッグ"},{name:"ショルダーバッグ"},{name:"クラッチバッグ"},{name:"ポーチ/バニティ"},{name:"ボディバッグ/ウェストバッグ"},{name:"マザーズバッグ"},{name:"メッセンジャーバッグ"},{name:"ビジネスバッグ"},{name:"旅行用バッグ/キャリーバッグ"},{name:"ショップ袋"},{name:"和服用バッグ"},{name:"かごバッグ"},{name:"その他"}])
category1_11.children.create([{name:"ネックレス"},{name:"ブレスレット"},{name:"バングル/リストバンド"},{name:"リング"},{name:"ピアス(片耳用)"},{name:"ピアス(両耳用)"},{name:"イヤリング"},{name:"アンクレット"},{name:"ブローチ/コサージュ"},{name:"チャーム"},{name:"その他"}])
category1_12.children.create([{name:"ヘアゴム/シュシュ"},{name:"ヘアバンド/カチューシャ"},{name:"ヘアピン"},{name:"その他"}])
category1_13.children.create([{name:"長財布"},{name:"折り財布"},{name:"コインケース/小銭入れ"},{name:"キーケース"},{name:"キーホルダー"},{name:"手袋/アームカバー"},{name:"ハンカチ"},{name:"ベルト"},{name:"マフラー/ショール"},{name:"ストール/スヌード"}, {name:"バンダナ/スカーフ"},{name:"ネックウォーマー"},{name:"サスペンダー"},{name:"サングラス/メガネ"},{name:"モバイルケース/カバー"},{name:"手帳"},{name:"イヤマフラー"},{name:"傘"},{name:"レインコート/ポンチョ"},{name:"ミラー"},{name:"タバコグッズ"},{name:"その他"}])
category1_14.children.create([{name:"腕時計(アナログ)"},{name:"腕時計(デジタル)"},{name:"ラバーベルト"},{name:"レザーベルト"},{name:"金属ベルト"},{name:"その他"}])
category1_15.children.create([{name:"前髪ウィッグ"},{name:"ロングスカート"},{name:"ロングカール"},{name:"ショートストレート"},{name:"ショートカール"},{name:"その他"}])
category1_16.children.create([{name:"浴衣"},{name:"着物"},{name:"振袖"},{name:"長襦袢/半襦袢"},{name:"水着セパレート"},{name:"水着ワンピース"},{name:"水着スポーツ用"},{name:"その他"}])
category1_17.children.create([{name:"スカートスーツ上下"},{name:"パンツスーツ上下"},{name:"ドレス"},{name:"パーティーバッグ"},{name:"シューズ"},{name:"ウェディング"},{name:"その他"}])
category1_18.children.create([{name:"トップス"},{name:"アウター"},{name:"インナー"},{name:"ワンピース"},{name:"パンツ/スパッツ"},{name:"スカート"},{name:"パジャマ"},{name:"授乳服"},{name:"その他"}])
category1_19.children.create([{name:"コスプレ"},{name:"下着"},{name:"その他"}])
category2_1.children.create([{name:"Tシャツ/カットソー(半袖/袖なし)"},{name:"Tシャツ/カットソー(七分/長袖)"},{name:"シャツ"},{name:"ポロシャツ"},{name:"タンクトップ"},{name:"ニット/セーター"},{name:"パーカー"},{name:"カーディガン"},{name:"スウェット"},{name:"ジャージ"},{name:"ベスト"},{name:"その他"}])
category2_2.children.create([{name:"テーラードジャケット"},{name:"ノーカラージャケット"},{name:"Gジャン/デニムジャケット"},{name:"レザージャケット"},{name:"ダウンジャケット"},{name:"ライダースジャケット"},{name:"ミリタリージャケット"},{name:"ナイロンジャケット"},{name:"フライトジャケット"},{name:"ダッフルコート"},{name:"ピーコート"},{name:"ステンカラーコート"},{name:"トレンチコート"},{name:"モッズコート"},{name:"チェスターコート"},{name:"スタジャン"},{name:"スカジャン"},{name:"ブルゾン"},{name:"マウンテンパーカー"},{name:"ダウンベスト"},{name:"ポンチョ"},{name:"カバーオール"},{name:"その他"}])
category2_3.children.create([{name:"デニム/ジーンズ"},{name:"ワークパンツ/カーゴパンツ"},{name:"スラックス"},{name:"チノパン"},{name:"ショートパンツ"},{name:"サルエルパンツ"},{name:"オーバーオール"},{name:"その他"}])
category2_4.children.create([{name:"スニーカー"},{name:"サンダル"},{name:"モカシン"},{name:"ドレス/ビジネス"},{name:"長靴/レインシューズ"},{name:"デッキシューズ"},{name:"その他"}])
category2_5.children.create([{name:"ショルダーバッグ"},{name:"トートバッグ"},{name:"ボストンバッグ"},{name:"リュック/バックパック"},{name:"ウェストポーチ"},{name:"ドラムバッグ"},{name:"ビジネスバッグ"},{name:"トラベルバッグ"},{name:"メッセンジャーバッグ"},{name:"エコバッグ"},{name:"その他"}])
category2_6.children.create([{name:"スーツジャケット"},{name:"スーツベスト"},{name:"スラックス"},{name:"セットアップ"},{name:"その他"}])
category2_7.children.create([{name:"キャップ"},{name:"ハット"},{name:"ニットキャップ/ビーニー"},{name:"キャスケット"},{name:"サンバイザー"},{name:"その他"}])
category2_8.children.create([{name:"ネックレス"},{name:"ブレスレット"},{name:"バングル/リストバンド"},{name:"リング"},{name:"ピアス(片耳用)"},{name:"ピアス(両耳用)"},{name:"アンクレット"},{name:"その他"}])
category2_9.children.create([{name:"長財布"},{name:"折り財布"},{name:"マネークリップ"},{name:"コインケース/小銭入れ"},{name:"名刺入れ/定期入れ"},{name:"キーケース"},{name:"キーホルダー"},{name:"ネクタイ"},{name:"手袋"},{name:"ハンカチ"},{name:"ベルト"},{name:"マフラー"},{name:"ストール"},{name:"バンダナ"},{name:"ネックウォーマー"},{name:"サスペンダー"},{name:"ウォレットチェーン"},{name:"サングラス/メガネ"},{name:"モバイルケース/カバー"},{name:"手帳"},{name:"ストラップ"},{name:"ネクタイピン"},{name:"カフリンクス"},{name:"イヤマフラー"},{name:"傘"},{name:"レインコート"},{name:"ミラー"},{name:"タバコグッズ"},{name:"その他"}])
category2_10.children.create([{name:"腕時計(アナログ)"},{name:"腕時計(デジタル)"},{name:"ラバーベルト"},{name:"レザーベルト"},{name:"金属ベルト"},{name:"その他"}])
category2_11.children.create([{name:"一般水着"},{name:"スポーツ用"},{name:"アクセサリー"},{name:"その他"}])
category2_12.children.create([{name:"ソックス"},{name:"レギンス/スパッツ"},{name:"レッグウォーマー"},{name:"その他"}])
category2_13.children.create([{name:"トランクス"},{name:"ボクサーパンツ"},{name:"その他"}])
category3_1.children.create([{name:"トップス"},{name:"アウター"},{name:"パンツ"},{name:"スカート"},{name:"ワンピース"},{name:"ベビードレス"},{name:"おくるみ"},{name:"下着/肌着"},{name:"パジャマ"},{name:"ロンパース"},{name:"その他"}])
category3_2.children.create([{name:"トップス"},{name:"アウター"},{name:"パンツ"},{name:"スカート"},{name:"ワンピース"},{name:"おくるみ"},{name:"下着/肌着"},{name:"パジャマ"},{name:"ロンパース"},{name:"その他"}])
category3_3.children.create([{name:"トップス"},{name:"アウター"},{name:"パンツ"},{name:"スカート"},{name:"ワンピース"},{name:"おくるみ"},{name:"下着/肌着"},{name:"パジャマ"},{name:"ロンパース"},{name:"その他"}])
category3_4.children.create([{name:"コート"},{name:"トップス(Tシャツ/カットソー)"},{name:"トップス(トレーナー)"},{name:"トップス(タンクトップ)"},{name:"トップス(その他)"},{name:"スカート"},{name:"パンツ"},{name:"ワンピース"},{name:"セットアップ"},{name:"パジャマ"},{name:"フォーマルドレス"},{name:"和服"},{name:"浴衣"},{name:"甚平"},{name:"水着"},{name:"その他"}])
category3_5.children.create([{name:"コート"},{name:"トップス(Tシャツ/カットソー)"},{name:"トップス(トレーナー)"},{name:"トップス(タンクトップ)"},{name:"トップス(その他)"},{name:"スカート"},{name:"パンツ"},{name:"ワンピース"},{name:"セットアップ"},{name:"パジャマ"},{name:"フォーマルドレス"},{name:"和服"},{name:"浴衣"},{name:"甚平"},{name:"水着"},{name:"その他"}])
category3_6.children.create([{name:"コート"},{name:"ジャケット/上着"},{name:"トップス(トレーナー)"},{name:"トップス(その他)"},{name:"ボトムス"},{name:"パジャマ"},{name:"その他"}])
category3_7.children.create([{name:"スニーカー"},{name:"サンダル"},{name:"ブーツ"},{name:"長靴"},{name:"その他"}])
category3_8.children.create([{name:"靴下/スパッツ"},{name:"帽子"},{name:"エプロン"},{name:"サスペンダー"},{name:"タイツ"},{name:"ハンカチ"},{name:"バンダナ"},{name:"ベルト"},{name:"マフラー"},{name:"傘"},{name:"手袋"},{name:"スタイ"},{name:"バッグ"},{name:"その他"}])
category3_9.children.create([{name:"おむつ用品"},{name:"おまる/補助便座"},{name:"トレーニングパンツ"},{name:"ベビーバス"},{name:"お風呂用品"},{name:"その他"}])
category3_10.children.create([{name:"ベビーカー"},{name:"抱っこひも/スリング"},{name:"チャイルドシート"},{name:"その他"}])
category3_11.children.create([{name:"ミルク"},{name:"ベビーフード"},{name:"ベビー用食器"},{name:"その他"}])
category3_12.children.create([{name:"ベッド"},{name:"布団/毛布"},{name:"イス"},{name:"たんす"},{name:"その他"}])
category3_13.children.create([{name:"おふろのおもちゃ"},{name:"ガラガラ"},{name:"オルゴール"},{name:"ベビージム"},{name:"手押し車/カタカタ"},{name:"知育玩具"},{name:"その他"}])
category3_14.children.create([{name:"お宮参り用品"},{name:"お食い初め用品"},{name:"アルバム"},{name:"手形/足形"},{name:"その他"}])
category3_15.children.create([{name:"母子手帳用品"},{name:"その他"}])
category4_1.children.create([{name:"食器"},{name:"調理器具"},{name:"収納/キッチン雑貨"},{name:"弁当用品"},{name:"カトラリー(スプーン等)"},{name:"テーブル用品"},{name:"容器"},{name:"エプロン"},{name:"アルコールグッズ"},{name:"浄水器"},{name:"その他"}])
category4_2.children.create([{name:"セミシングルベッド"},{name:"シングルベッド"},{name:"セミダブルベッド"},{name:"ダブルベッド"},{name:"ワイドダブルベッド"},{name:"クイーンベッド"},{name:"キングベッド"},{name:"脚付きマットレスベッド"},{name:"マットレス"},{name:"すのこベッド"},{name:"ロフトベッド"},{name:"ロフトベッド/システムベッド"},{name:"簡易ベッド/折りたたみベッド"},{name:"収納付き"},{name:"その他"}])
category4_3.children.create([{name:"ソファセット"},{name:"シングルソファ"},{name:"ラブソファ"},{name:"トリプルソファ"},{name:"オットマン"},{name:"コーナーソファ"},{name:"ビーズソファ/クッション"},{name:"ローソファ/フロアソファ"},{name:"応援セット"},{name:"ソファカバー"},{name:"リクライニングソファ"},{name:"その他"}])
category4_4.children.create([{name:"一般"},{name:"スツール"},{name:"ダイニングチェア"},{name:"ハイバックチェア"},{name:"ロッキングチェア"},{name:"座椅子"},{name:"折り畳みイス"},{name:"デスクチェア"},{name:"その他"}])
category4_5.children.create([{name:"こたつ"},{name:"カウンターテーブル"},{name:"サイドテーブル"},{name:"センターテーブル"},{name:"ダイニングテーブル"},{name:"座卓/ちゃぶ台"},{name:"アウトドア用"},{name:"パソコン用"},{name:"事務机/学習机"},{name:"その他"}])
category4_6.children.create([{name:"リビング収納"},{name:"キッチン収納"},{name:"玄関/屋外収納"},{name:"バス/トイレ"},{name:"本収納"},{name:"本/CD/DVD収納"},{name:"洋服タンス/押入れ収納"},{name:"電話台/ファックス台"},{name:"ドレッサー/鏡台"},{name:"棚/ラック"},{name:"ケース/ボックス"},{name:"その他"}])
category4_7.children.create([{name:"ラグ"},{name:"カーペット"},{name:"ホットカーペット"},{name:"玄関/キッチンマット"},{name:"トイレ/バスマット"},{name:"その他"}])
category4_8.children.create([{name:"カーテン"},{name:"ブラインド"},{name:"ロールスクリーン"},{name:"のれん"},{name:"その他"}])
category4_9.children.create([{name:"蛍光灯/電球"},{name:"天井照明"},{name:"フロアスタンド"},{name:"その他"}])
category4_10.children.create([{name:"布団/毛布"},{name:"枕"},{name:"シーツ/カバー"},{name:"その他"}])
category4_11.children.create([{name:"ごみ箱"},{name:"ウェルカムボード"},{name:"オルゴール"},{name:"クッション"},{name:"クッションカバー"},{name:"スリッパラック"},{name:"バスケット/かご"},{name:"フォトフレーム"},{name:"マガジンラック"},{name:"モビール"},{name:"花瓶"},{name:"灰皿"},{name:"傘入れ"},{name:"置時計"},{name:"掛時計/柱時計"},{name:"鏡(立て掛け式)"},{name:"鏡(壁掛け式)"},{name:"置物"},{name:"風鈴"},{name:"植物/観葉植物"},{name:"その他"}])
category4_12.children.create([{name:"正月"},{name:"成人式"},{name:"バレンタインデー"},{name:"ひな祭り"},{name:"子どもの日"},{name:"母の日"},{name:"父の日"},{name:"サマーギフト/お中元"},{name:"夏/夏休み"},{name:"ハロウィン"},{name:"敬老の日"},{name:"七五三"},{name:"お歳暮"},{name:"クリスマス"},{name:"冬一般"},{name:"その他"}])
category5_1.children.create([{name:"文学/小説"},{name:"人文/社会"},{name:"ノンフィクション/教養"},{name:"地図/旅行ガイド"},{name:"ビジネス/経済"},{name:"健康/医学"},{name:"コンピュータ/IT"},{name:"趣味/スポーツ/実用"},{name:"住まい/暮らし/子育て"},{name:"アート/エンタメ"},{name:"洋書"},{name:"絵本"},{name:"参考書"},{name:"その他"}])
category5_2.children.create([{name:"全巻セット"},{name:"少年漫画"},{name:"青年漫画"},{name:"女性漫画"},{name:"同人誌"},{name:"その他"}])
category5_3.children.create([{name:"アート/エンタメ/ホビー"},{name:"ファッション"},{name:"ニュース/統合"},{name:"趣味/スポーツ"},{name:"その他"}])
category5_4.children.create([{name:"邦楽"},{name:"洋楽"},{name:"アニメ"},{name:"クラシック"},{name:"K-POP/アジア"},{name:"キッズ/ファミリー"},{name:"その他"}])
category5_5.children.create([{name:"外国映画"},{name:"日本映画"},{name:"アニメ"},{name:"TVドラマ"},{name:"ミュージック"},{name:"お笑い/バラエティ"},{name:"スポーツ/フィットネス"},{name:"キッズ/ファミリー"},{name:"その他"}])
category5_6.children.create([{name:"邦楽"},{name:"洋楽"},{name:"その他"}])
category5_7.children.create([{name:"家庭用ゲーム本体"},{name:"家庭用ゲームソフト"},{name:"携帯用ゲーム本体"},{name:"携帯用ゲームソフト"},{name:"PCゲーム"},{name:"その他"}])
category6_1.children.create([{name:"キャラクターグッズ"},{name:"ぬいぐるみ"},{name:"小物/アクセサリー"},{name:"模型/プラモデル"},{name:"ミニカー"},{name:"トイラジコン"},{name:"プラモデル"},{name:"ホビーラジコン"},{name:"鉄道模型"},{name:"その他"}])
category6_2.children.create([{name:"アイドル"},{name:"ミュージシャン"},{name:"タレント/お笑い芸人"},{name:"スポーツ選手"},{name:"その他"}])
category6_3.children.create([{name:"ストラップ"},{name:"キーホルダー"},{name:"バッジ"},{name:"カード"},{name:"クリアファイル"},{name:"ポスター"},{name:"タオル"},{name:"その他"}])
category6_4.children.create([{name:"遊戯王"},{name:"マジック：ザ・ギャザリング"},{name:"ポケモンカードゲーム"},{name:"デュエル・マスターズ"},{name:"バトルスピリッツ"},{name:"プリパラ"},{name:"アイカツ"},{name:"カードファイト!!ヴァンガード"},{name:"ヴァイスシュバルツ"},{name:"プロ野球オーナーズリーグ"},{name:"ベースボールヒーローズ"},{name:"ドラゴンボール"},{name:"スリープ"},{name:"その他"}])
category6_5.children.create([{name:"コミック/アニメ"},{name:"特撮"},{name:"ゲームキャラクター"},{name:"SF/ファンタジー/ホラー"},{name:"アメコミ"},{name:"スポーツ"},{name:"ミリタリー"},{name:"その他"}])
category6_6.children.create([{name:"エレキギター"},{name:"アコースティックギター"},{name:"ベース"},{name:"エフェクター"},{name:"アンプ"},{name:"弦楽器"},{name:"管楽器"},{name:"鍵盤楽器"},{name:"打楽器"},{name:"和楽器"},{name:"楽譜/スコア"},{name:"レコーディング/PA機器"},{name:"DJ機器"},{name:"DTM/DAW"},{name:"その他"}])
category6_7.children.create([{name:"武具"},{name:"使用済切手/官製はがき"},{name:"印刷物"},{name:"ノベルティグッズ"},{name:"その他"}])
category6_8.children.create([{name:"トイガン"},{name:"個人装備"},{name:"その他"}])
category6_9.children.create([{name:"陶芸"},{name:"ガラス"},{name:"漆芸"},{name:"金属工芸"},{name:"絵画/タペストリ"},{name:"版画"},{name:"彫刻/オブジェクト"},{name:"書"},{name:"写真"},{name:"その他"}])
category6_10.children.create([{name:"画材"},{name:"額縁"},{name:"その他"}])
category6_11.children.create([{name:"トランプ/UNO"},{name:"カルタ/百人一首"},{name:"ダーツ"},{name:"ビリヤード"},{name:"麻雀"},{name:"パズル/ジグソーパズル"},{name:"囲碁/将棋"},{name:"オセロ/チェス"},{name:"人生ゲーム"},{name:"野球/サッカーゲーム"},{name:"スポーツ"},{name:"三輪車/乗り物"},{name:"ヨーヨー"},{name:"模型製作用品"},{name:"鉄道"},{name:"航空機"},{name:"アマチュア無線"},{name:"パチンコ/パチスロ"},{name:"その他"}])
category7_1.children.create([{name:"ファンデーション"},{name:"化粧下地"},{name:"コントロールカラー"},{name:"BBクリーム"},{name:"CCクリーム"},{name:"コンシーラー"},{name:"フェイスパウダー"},{name:"トライアルセット/サンプル"},{name:"その他"}])
category7_2.children.create([{name:"アイシャドウ"},{name:"口紅"},{name:"リップグロス"},{name:"リップライナー"},{name:"チーク"},{name:"フェイスカラー"},{name:"マスカラ"},{name:"アイライナー"},{name:"つけまつげ"},{name:"アイブロウペンシル"},{name:"パウダーアイブロー"},{name:"眉マスカラ"},{name:"トライアルセット/サンプル"},{name:"メイク道具/化粧小物"},{name:"美顔用品/美顔ローラー"},{name:"その他"}])
category7_3.children.create([{name:"ネイルカラー"},{name:"カラージェル"},{name:"ネイルベースコート/トップコート"},{name:"ネイルアート用品"},{name:"ネイルパーツ"},{name:"ネイルチップ/付け爪"},{name:"手入れ用具"},{name:"除光液"},{name:"その他"}])
category7_4.children.create([{name:"香水(女性用)"},{name:"香水(男性用)"},{name:"ユニセックス"},{name:"ボディミスト"},{name:"その他"}])
category7_5.children.create([{name:"化粧水/ローション"},{name:"乳液/ミルク"},{name:"美容液"},{name:"フェイスクリーム"},{name:"洗顔料"},{name:"クレンジング/メイク落とし"},{name:"パック/フェイスマスク"},{name:"ジェル/ゲル"},{name:"ブースター/導入液"},{name:"アイケア"},{name:"リップケア"},{name:"トライアルセット/サンプル"},{name:"洗顔グッズ"},{name:"その他"}])
category7_6.children.create([{name:"シャンプー"},{name:"トリートメント"},{name:"コンディショナー"},{name:"リンス"},{name:"スタイリング剤"},{name:"カラーリング剤"},{name:"ブラシ"},{name:"その他"}])
category7_7.children.create([{name:"オイル/クリーム"},{name:"ハンドクリーム"},{name:"ローション"},{name:"日焼け止め/サンオイル"},{name:"ボディソープ"},{name:"入浴剤"},{name:"制汗/デオドラント"},{name:"フットケア"},{name:"その他"}])
category7_8.children.create([{name:"口臭防止/エチケット用品"},{name:"歯ブラシ"},{name:"その他"}])
category7_9.children.create([{name:"エッセンシャルオイル"},{name:"芳香機"},{name:"お香/香炉"},{name:"キャンドル"},{name:"リラクゼーショングッズ"},{name:"その他"}])
category7_10.children.create([{name:"ダイエット食品"},{name:"エクササズ用品"},{name:"体重計"},{name:"体脂肪計"},{name:"その他"}])
category7_11.children.create([{name:"健康用品"},{name:"介護/介護用品"},{name:"救急/衛生用品"},{name:"その他"}])
category8_1.children.create([{name:"スマートフォン本体"},{name:"バッテリー/充電器"},{name:"携帯電話本体"},{name:"PHS本体"},{name:"その他"}])
category8_2.children.create([{name:"スマホアクセサリー"},{name:"Android用ケース"},{name:"iPhone用ケース"},{name:"カバー"},{name:"イヤホンジャック"},{name:"ストラップ"},{name:"フィルム"},{name:"自撮り棒"},{name:"その他"}])
category8_3.children.create([{name:"タブレット"},{name:"ノートPC"},{name:"デスクトップ型PC"},{name:"ディスプレイ"},{name:"電子ブックリーダー"},{name:"PC周辺機器"},{name:"PCパーツ"},{name:"その他"}])
category8_4.children.create([{name:"デジタルカメラ"},{name:"ビデオカメラ"},{name:"レンズ(単焦点)"},{name:"レンズ(ズーム)"},{name:"フィルムカメラ"},{name:"防犯カメラ"},{name:"その他"}])
category8_5.children.create([{name:"テレビ"},{name:"プロジェクター"},{name:"ブルーレイレコーダー"},{name:"DVDレコーダー"},{name:"ブルーレイプレイヤー"},{name:"DVDプレイヤー"},{name:"映像用ケーブル"},{name:"その他"}])
category8_6.children.create([{name:"ポータブルプレイヤー"},{name:"イヤフォン"},{name:"ヘッドフォン"},{name:"アンプ"},{name:"スピーカー"},{name:"ケーブル/シールド"},{name:"ラジオ"},{name:"その他"}])
category8_7.children.create([{name:"ヘアドライヤー"},{name:"ヘアアイロン"},{name:"美容機器"},{name:"電気シェーバー"},{name:"電動歯ブラシ"},{name:"その他"}])
category8_8.children.create([{name:"エアコン"},{name:"空気清浄機"},{name:"加湿器"},{name:"扇風機"},{name:"除湿機"},{name:"ファンヒーター"},{name:"電気ヒーター"},{name:"オイルヒーター"},{name:"ストーブ"},{name:"ホットカーペット"},{name:"こたつ"},{name:"電気毛布"},{name:"その他"}])
category8_9.children.create([{name:"冷蔵庫"},{name:"洗濯機"},{name:"炊飯器"},{name:"電子レンジ/オーブン"},{name:"調理機器"},{name:"アイロン"},{name:"エスプレッソマシン"},{name:"コーヒーメーカー"},{name:"衣類乾燥機"},{name:"その他"}])
category8_10.children.create([{name:"その他"}])
category9_1.children.create([{name:"クラブ"},{name:"ウエア(男性用)"},{name:"ウエア(女性用)"},{name:"バッグ"},{name:"シューズ(男性用)"},{name:"シューズ(女性用)"},{name:"アクセサリー"},{name:"その他"}])
category9_2.children.create([{name:"ロッド"},{name:"リール"},{name:"ルアー用品"},{name:"ウエア"},{name:"釣り糸/ライン"},{name:"その他"}])
category9_3.children.create([{name:"自転車本体"},{name:ウエア},{name:"パーツ"},{name:"アクセサリー"},{name:"バッグ"},{name:"工具/メンテナンス"},{name:"その他"}])
category9_4.children.create([{name:"ランニング"},{name:"ウォーキング"},{name:"ヨガ"},{name:"トレーニング用品"},{name:"その他"}])
category9_5.children.create([{name:"ウェア"},{name:"シューズ"},{name:"グローブ"},{name:"バット"},{name:"アクセサリー"},{name:"防具"},{name:"練習機器"},{name:"記念グッズ"},{name:"応援グッズ"},{name:"その他"}])
category9_6.children.create([{name:"ウェア"},{name:"シューズ"},{name:"ボール"},{name:"アクセサリー"},{name:"記念グッズ"},{name:"応援グッズ"},{name:"その他"}])
category9_7.children.create([{name:"ラケット(硬式用)"},{name:"ラケット(軟式用)"},{name:"ウェア"},{name:"シューズ"},{name:"ボール"},{name:"アクセサリー"},{name:"記念グッズ"},{name:"応援グッズ"},{name:"その他"}])
category9_8.children.create([{name:"ボード"},{name:"バインディング"},{name:"ブーツ(男性用)"},{name:"ブーツ(女性用)"},{name:"ブーツ(子ども用)"},{name:"ウエア/装備(男性用)"},{name:"ウエア/装備(女性用)"},{name:"ウエア/装備(子ども用)"},{name:"アクセサリー"},{name:"バッグ"},{name:"その他"}])
category9_9.children.create([{name:"板"},{name:"ブーツ(男性用)"},{name:"ブーツ(女性用)"},{name:"ブーツ(子ども用)"},{name:"ストック"},{name:"その他"}])
category9_10.children.create([{name:"ダンス/バレエ"},{name:"サーフィン"},{name:"バスケットボール"},{name:"バドミントン"},{name:"バレーボール"},{name:"スケートボード"},{name:"陸上競技"},{name:"ラグビー"},{name:"アメリカンフットボール"},{name:"ボクシング"},{name:"ボウリング"},{name:"その他"}])
category9_11.children.create([{name:"テント/タープ"},{name:"ライト/ランタン"},{name:"寝袋/寝具"},{name:"テーブル/チェア"},{name:"ストーブ/コンロ"},{name:"調理器具"},{name:"食器"},{name:"登山用品"},{name:"その他"}])
category9_12.children.create([{name:"旅行用品"},{name:"その他"}])
category10_1.children.create([{name:"ピアス"},{name:"イヤリング"},{name:"ネックレス"},{name:"ブレスレット"},{name:"リング"},{name:"チャーム"},{name:"ヘアゴム"},{name:"アンクレット"},{name:"その他"}])
category10_2.children.create([{name:"バッグ(女性用)"},{name:"バッグ(男性用)"},{name:"財布(女性用)"},{name:"財布(男性用)"},{name:"ファッション雑貨"},{name:"その他"}])
category10_3.children.create([{name:"アクセサリー(男性用)"},{name:"時計(女性用)"},{name:"時計(男性用)"},{name:"その他"}])
category10_4.children.create([{name:"キッチン用品"},{name:"家具"},{name:"文房具"},{name:"アート/写真"},{name:"アロマ/キャンドル"},{name:"フラワー/ガーデン"},{name:"その他"}])
category10_5.children.create([{name:"クラフト/布製品"},{name:"おもちゃ/人形"},{name:"その他"}])
category10_6.children.create([{name:"ファッション雑貨"},{name:"スタイ/よだれかけ"},{name:"外出用品"},{name:"ネームタグ"},{name:"その他"}])
category10_7.children.create([{name:"各種パーツ"},{name:"生地/糸"},{name:"型紙/パターン"},{name:"その他"}])
category10_8.children.create([{name:"ingress"},{name:"クリエーターズ宇宙兄弟"}])
category11_1.children.create([{name:"男性アイドル"},{name:"女性アイドル"},{name:"韓流"},{name:"国内アーティスト"},{name:"海外アーティスト"},{name:"音楽フェス"},{name:"声優/アニメ"},{name:"その他"}])
category11_2.children.create([{name:"サッカー"},{name:"野球"},{name:"テニス"},{name:"格闘技/プロレス"},{name:"相撲/プロレス"},{name:"ゴルフ"},{name:"バレーボール"},{name:"バスケットボール"},{name:"モータースポーツ"},{name:"ウィンタースポーツ"},{name:"その他"}])
category11_3.children.create([{name:"ミュージカル"},{name:"演劇"},{name:"伝統芸能"},{name:"落語"},{name:"お笑い"},{name:"オペラ"},{name:"サーカス"},{name:"バレエ"},{name:"その他"}])
category11_4.children.create([{name:"声優/アニメ"},{name:"キッズ/ファミリー"},{name:"トークショー/講演会"},{name:"その他"}])
category11_5.children.create([{name:"邦画"},{name:"洋画"},{name:"その他"}])
category11_6.children.create([{name:"遊園地 /テーマパーク"},{name:"美術館/博物館"},{name:"スキー場"},{name:"ゴルフ場"},{name:"フィットネスクラブ"},{name:"プール"},{name:"ボウリング場"},{name:"水族館"},{name:"動物園"},{name:"その他"}])
category11_7.children.create([{name:"ショッピング"},{name:"レストラン/食事券"},{name:"フード/ドリンク券"},{name:"宿泊券"},{name:"その他"}])
category12_1.children.create([{name:"国内自動車本体"},{name:"外国自動車本体"}])
category12_2.children.create([{name:"タイヤ/ホイールセット"},{name:"タイヤ"},{name:"ホイール"},{name:"その他"}])
category12_3.children.create([{name:"サスペンション"},{name:"ブレーキ"},{name:"外装、エアロパーツ"},{name:"ライト"},{name:"内装品/シート"},{name:"ステアリング"},{name:"マフラー・排気系"},{name:"エンジン、過給機、冷却装置"},{name:"クラッチ、ミッション、駆動系"},{name:"電装品"},{name:"補強パーツ"},{name:"汎用パーツ"},{name:"外国自動車用パーツ"},{name:"その他"}])
category12_4.children.create([{name:"車内アクセサリー"},{name:"カーナビ"},{name:"カーオーディオ"},{name:"車外アクセサリー"},{name:"メンテナンス用品"},{name:"チャイルドシート"},{name:"ドライブレコーダー"},{name:"レコーダー探知機"},{name:"カタログ/マニュアル"},{name:"セキュリティ"},{name:"ETC"},{name:"その他"}])
category12_6.children.create([{name:"タイヤ"},{name:"マフラー"},{name:"エンジン、冷却装置"},{name:"カウル、フェンダー、外装"},{name:"サスペンション"},{name:"ホイール"},{name:"シート"},{name:"ブレーキ"},{name:"タンク"},{name:"ライト、ウィンカー"},{name:"チェーン、スプロケット、駆動系"},{name:"メーター"},{name:"電装系"},{name:"ミラー"},{name:"外国オートバイ用パーツ"},{name:"その他"}])
category12_7.children.create([{name:"ヘルメット/シールド"},{name:"バイクウエア/装備"},{name:"アクセサリー"},{name:"メンテナンス"},{name:"カタログ/マニュアル"},{name:"その他"}])
category13_2.children.create([{name:"ペットフード"},{name:"犬用品"},{name:"猫用品"},{name:"魚用品/水草"},{name:"小動物用品"},{name:"爬虫類/両生類用品"},{name:"かご/おり"},{name:"鳥用品"},{name:"虫類用品"},{name:"その他"}])
category13_3.children.create([{name:"菓子"},{name:"米"},{name:"野菜"},{name:"果物"},{name:"調味料"},{name:"魚介類(加工品)"},{name:"肉類(加工品)"},{name:"その他加工品"},{name:"その他"}])
category13_4.children.create([{name:"コーヒー"},{name:"ソフトドリンク"},{name:"ミネラルウォーター"},{name:"茶"},{name:"ウィスキー"},{name:"ワイン"},{name:"ブランデー"},{name:"焼酎"},{name:"日本酒"},{name:"ビール、発泡酒"},{name:"その他"}])
category13_5.children.create([{name:"タオル/バス用品"},{name:"日用品/生活雑貨"},{name:"洗剤/柔軟剤"},{name:"旅行用品"},{name:"防災関連グッズ"},{name:"その他"}])
category13_6.children.create([{name:"雑貨"},{name:"工芸品"},{name:"家具"},{name:"印刷物"},{name:"その他"}])
category13_7.children.create([{name:"筆記用具"},{name:"ノート/メモ帳"},{name:"テープ/マスキングテープ"},{name:"カレンダー/スケジュール"},{name:"アルバム/スクラップ"},{name:"ファイル/バインダー"},{name:"はさみ/カッター"},{name:"カードホルダー/名刺管理"},{name:"のり/ホッチキス"},{name:"その他"}])
category13_8.children.create([{name:"オフィス用品一般"},{name:"オフィス家具"},{name:"店舗用品"},{name:"OA機器"},{name:"ラッピング/包装"},{name:"その他"}])






